core/urls.py
from django.urls import path
from core.views import *

app_name = 'core'

urlpatterns = [
    path('',home,name='home'),
    path('games',games,name="games"),
    path('dates',dates,name="dates"),
    path('detailpages/<int:id>/',detailpages,name="detailpages")
]

minecraft/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models








class Games(models.Model):
    image = models.ImageField(upload_to='games/')
    title = models.CharField(max_length=300)
    describtions = models.TextField()
    price = models.CharField(max_length=300)


    def __str__(self):
        return self.title


class Post(models.Model):
    image = models.ImageField(upload_to='post/')
    title = models.CharField(max_length=300)
    describtions = models.TextField()

    def __str__(self):
        return self.title


class News(models.Model):
    image = models.ImageField(upload_to='news/')
    title = models.CharField(max_length=300)        
   
    def __str__(self):
        return self.title
 
 

# Create your models here.

core/views.py
from django.shortcuts import render
from core.models import *

def home(request):
    games = Games.objects.all()
    posts = Post.objects.all()
    news = News.objects.all()
    context = {
        'games': games,
        'posts': posts,
        'news': news,
    }
    return render(request,'index.html',context)

def games(request):
    games = Games.objects.order_by('-id')
    context = {
        'games': games,

    }

    return render(request,'games.html',context)

def dates(request):
   
    return render(request,'dates.html')

def detailpages(request,id):
    game = Games.objects.get(id=id)
    games = Games.objects.all()
    context = {
        'game':game,
        'games':games
    }
    return render(request,'detailpages.html',context)    
# Create your views here.

core/templates/games.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="">
<style>
  a{
    text-decoration: none !important;
  }
</style>
</head>
<body style="background-color: black;">


     <nav class="navbar navbar-expand-lg navbar-dark ">
  <a class="navbar-brand" href="{% url 'core:home' %}"><img style="width: 200px;" src="https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/logos/Global-Header_MCCB-Logo_300x51.svg" alt=""></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul style="margin-left: 250px;" class="navbar-nav mr-auto">
       <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:home' %}">Домь <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:games' %}">Игры  </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Магазин</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Новости
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#"></a>
          <a class="dropdown-item" href="#"></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#"></a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link  " href="#">Поддержка</a>
      </li>
       <li class="nav-item">
        <a class="nav-link  " href="{% url 'core:dates' %}">Дата</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      
    </form>
  </div>
</nav>

    <div>
        <h1 style="color: white;font-weight: bold;text-align: center;">Choose Your Game</h1>
        <p style="color: white;text-align: center;">Explore different editions and dive into the world that suits your playstyle!</p>
    </div>



    <div>
        <div class="container-fluid">
	<div class="row">
    {% for game in games %}
    <a href="{% url 'core:detailpages' game.id  %}">

		<div class="col-md-3">
            <div class="card" style="width: 18rem;background-color: black;">
  <img class="card-img-top" src="{{game.image}}" alt="Card image cap">
  <div class="card-body">
    <h5 style="color: white;" class="card-title">{{game.title}}</h5>
    <p style="color: white;" class="card-text">{{game.describtions  }}</p> 

    
  </div>
</div>
		</div>
    </a>

    {% endfor  %}
	 
	</div>
</div>
    </div>




    <div>
        <h1 style="color: white;font-weight: bold;text-align: center;margin-top: 50px;">SUBSCRIPTIONS</h1>
        <p style="color: white;text-align: center;margin-top: 10px;">Level-up your experience with additional content and ways to play with friends!</p>
    </div>


    <div style="background-color: rgb(36, 36, 36);">
        <div class="container-fluid">
	<div class="row">
		<div class="col-md-7">
            <img src="https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/marketplace/Media-Block-B_Marketplace-Pass_1200x800.jpg" alt="">
		</div>
		<div class="col-md-5">
            <h1 style="color: white;font-weight: bold;margin-top: 200px;margin-left: 150px;">Marketplace Pass</h1>
            <p  style="color: white;text-align: center;margin-top: 40px;">Play 150+ pieces of exciting content for one low monthly price with <br> Marketplace Pass! Dive into worlds, mash-ups, skins packs, texture <br> packs, and more. With fresh content added every month, there's <br> always something new to play with Marketplace Pass! *</p>
            <button style="background-color: #ffc42b;color: #071927;font-weight: 800;letter-spacing: .03em;text-transform: uppercase;padding: .9375rem 1.75rem;text-decoration: none;align-items: center;margin-left: 150px;">See subscription details</button>
		</div>
	</div>
</div>
    </div>




    
  </div>
  
  <div style="background-color: rgb(54, 3, 54);margin-top: -50px;height: 800px;">
    <div style="background-image: url(https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/key-art/Marketplace-Pass_Media-Block-Image-0_Realms_1200x480.png?imwidth=1200);height: 500px;margin-top: 50px;margin-left: 150px;background-color: rgb(54, 3, 54);">
      
    
    </div>
    <h1 style="color: white;font-weight: bold;text-align: center;">Подпишись на Realms и делись своим контентом</h1>
    <p style="color: white;text-align: center;">Запускай собственный сервер Minecraft и делись с друзьями предметами, доступными с пропуском Marketplace (ты можешь выбрать до <br> 10 человек)! Играй по своим правилам: только ты решаешь, кого пригласить и как играть. Участники могут играть бесплатно, даже <br> когда ты не в сети. Простая настройка, управление и доступ с любого устройства.</p>
    <button style="color: white;font-weight: 800;letter-spacing: 0.3em;text-transform: uppercase;font-size: 1.125rem;line-height: 1.25rem;text-align: center;background-color: #7345e5;padding-right: 1;border: 2px solid black;min-width: 4.75rem;padding: 15px 28px;text-decoration: none;margin-left: 450px;">Смотреть подробности подписки</button>
  </div>




  <!-- Footer -->
<footer class="text-center text-lg-start bg-body-tertiary text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->























    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>  




</body>
</html>

core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="">
<style>
  a {
    text-decoration: none !important;
  }
</style>

</head>
<body style="background-color: black;">
    <nav class="navbar navbar-expand-lg navbar-dark ">
  <a class="navbar-brand" href="#"><img style="width: 200px;" src="https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/logos/Global-Header_MCCB-Logo_300x51.svg" alt=""></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul style="margin-left: 250px;" class="navbar-nav mr-auto">
       <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:home' %}">Домь <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:games' %}">Игры  </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Магазин</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Новости
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#"></a>
          <a class="dropdown-item" href="#"></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#"></a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link  " href="#">Поддержка</a>
      </li>
       <li class="nav-item">
        <a class="nav-link  " href="{% url 'core:dates' %}">Дата</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      
    </form>
  </div>
</nav>

<div>
    <img style="width: 100%;" src="https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/key-art/MC_ThreeStripesCity_Homepage_1920x1080.jpg" alt="">
    <div style="margin-top: -100px;margin-left: 100px ;">
        <h1 style="color: white;">Возвращение adidas x <br> Minecraft</h1>
        <p style="color: white;">Открой новую коллекцию adidas в реальной <br> жизни и в игре с захватывающим динамичным <br> миром. Проходи испытания и раскрывай секреты <br> в Городе Трех Полосок!</p>
        <button style="background-color: #3c8527; border: none;padding: 15px;color: white;"> Загрузить DLC</button>
        <img src="http://minecraft.net/content/dam/minecraftnet/games/minecraft/key-art/MC_ThreeStripesCity_Homepage_220x97.jpg" alt="">
        <img src="https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/key-art/Homepage_Hero-A-Thumbnail-0_Friendly-Fishing_220x97_01.jpg" alt="">
        <img src="https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/key-art/Minecraft_HuggyFriends_.net_220x97.jpg" alt="">
        <img src="https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/key-art/MCEDU_HOAI_TFN_MCEDUSocial_Supporting_220x97.png" alt="">
    </div>
</div>

<div style="background-color: black;">
    <h1 style="text-align: center;margin-top: 50px;color: white;">Познакомься с нашими играми</h1>

    <div class="container-fluid">
	<div class="row">
    {% for game in games %}
    
    <div class="col-md-3">
        <a href="{% url 'core:detailpages' game.id  %}">
        <div  class="card" style="width: 18rem;background-color: black;">
          <img class="card-img-top" src="{{game.image}}" alt="Card image cap">
          <div class="card-body">
            <h5 style="color: white;" class="card-title">{{game.title}}</h5>
            <p style="color: white;" class="card-text">{{game.describtion}}</p>
            
          </div>
        </div>
      </a>
      </div>



    {% endfor %}
		 
	</div>
</div>
</div>


<div>
  <h1 style="color: white;text-align: center;">СВЕЖИЕ НОВОСТИ</h1>
  
<div>
  <div class="container-fluid">
	<div class="row">
    
    {% for new in news %}
		<div class="col-md-3">
      <div class="card" style="height: 18rem;background-image: url({{new.image.url}});background-size: cover; background-repeat: no-repeat; margin-top: 10px; ">
  
  <div style="background: linear-gradient(to right, rgba(0, 0, 0, 137),rgba(0, 0, 0, 0.345));height: 150px;margin-top: 180px" class="">
    <h6 style="background-color: white;width: 90px;margin-top: 20px;">{{ new.title  }}</h6>
    
  
  </div>
</div>
</div>
{% endfor %}
	
		
		
	</div>
 
</div>

<br><br><br>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-4">
      <h1 style="color: white;">Коллекционные предметы</h1>
      <p style="color: white;">Мир Minecraft огромен. Почему бы не выйти за пределы <br> его блочных границ? Укрась свое устройство нашими <br> любимыми обоями, баннерами соцсетей и другими <br> элементами от Minecraft.
</p>
		</div>
		<div class="col-md-8">
      <img style="width: 18rem;height: 18rem;" src="https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/marketplace/Homepage_Collectables-Carousel-H-0_Crocs_414x414_01.jpg" alt="">
      <img style="width: 18rem;height: 18rem;" src="https://www.minecraft.net/content/dam/minecraftnet/community/events/cy2024/15-year-anniversary/15YA-Hub_Collectables-Carousel-H-0_15YA_414x414_01.jpg" alt="">
      <img style="width: 18rem;height: 18rem;" src="https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/key-art/Homepage_Collectables-Carousel-H_Java-Bedrock_414x414_01.jpg" alt="">
		</div>
	</div>
</div>












<!-- Footer -->
<footer class="text-center text-lg-start bg-body-tertiary text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

  









<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>  
    
</body>
</html>